### ISSUE TITLE
Improve notification routing similar to grafana

### ISSUE THREAD

**Issue by Darkness4** [Darkness4/fc2-live-dl-go#42]
Implement:

- Basic notification labelling: "public", "internal"
- Rewrite `urls` to `endpoints`:

```yaml
urls: # Deprecated, but assume a empty selector (allow everything)
  - 'gotify://gotify.example.com/token'

endpoints:
  - urls: 
      - 'gotify://gotify.example1.com/token'
    selector: [] # Allow everything
    noPriority: ... # Override default rules
    includeTitleInMessage: ...
  - urls: 
      - 'gotify://gotify.example2.com/token'
      - 'gotify://gotify.example3.com/token'
    selector:
      - 'public' # Allowlist mode, notification with public label will go here
  - urls: 
      - 'gotify://gotify.example4.com/token'
    selector:
      - '-public' # Denylist mode, notification without "public" label will go here
  - urls: 
      - 'gotify://gotify.example5.com/token'
    selector: # Without public, with internal.
      - '-public'
      - 'internal'
```

Notifications can go through multiple endpoints only if the selector is not empty.
